import {
  CustomerTier,
  DemandType,
  InventoryPoolDto,
  OrderDto,
  ShippingMethod,
} from './types/index.js';

const DEMO_WAREHOUSE_ID = 'WH-ZURICH';

export const demoInventory: InventoryPoolDto[] = [
  {
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    availableToSell: 50,
  },
  {
    skuId: 'SKU-JACKET-002',
    warehouseId: DEMO_WAREHOUSE_ID,
    availableToSell: 30,
  },
];

export const demoOrders: OrderDto[] = [
  // Retail (8)
  {
    orderId: 'ORD-2024-RET-001',
    demandType: DemandType.RETAIL,
    channel: 'Retail',
    customerTier: CustomerTier.VIP,
    shippingMethod: ShippingMethod.EXPRESS,
    totalOrderValue: 145000,
    createdAt: '2024-01-03T09:15:00Z',
    requestedDeliveryDate: '2024-01-05T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 12,
    productName: 'Cloud Runner 2',
    customer: 'On Zurich Flagship',
  },
  {
    orderId: 'ORD-2024-RET-002',
    demandType: DemandType.RETAIL,
    channel: 'Retail',
    customerTier: CustomerTier.VIP,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 132000,
    createdAt: '2024-01-04T11:00:00Z',
    requestedDeliveryDate: '2024-01-08T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 10,
    productName: 'Cloud Runner 2',
    customer: 'On Berlin Store',
  },
  {
    orderId: 'ORD-2024-RET-003',
    demandType: DemandType.RETAIL,
    channel: 'Retail',
    customerTier: CustomerTier.VIP,
    shippingMethod: ShippingMethod.EXPRESS,
    totalOrderValue: 168500,
    createdAt: '2024-01-08T10:40:00Z',
    requestedDeliveryDate: '2024-01-11T18:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 9,
    productName: 'Cloud Runner 2',
    customer: 'On London Regent St',
  },
  {
    orderId: 'ORD-2024-RET-004',
    demandType: DemandType.RETAIL,
    channel: 'Retail',
    customerTier: CustomerTier.VIP,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 120000,
    createdAt: '2024-01-09T14:20:00Z',
    requestedDeliveryDate: '2024-01-14T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 8,
    productName: 'Cloud Runner 2',
    customer: 'On Tokyo Shibuya',
  },
  {
    orderId: 'ORD-2024-RET-005',
    demandType: DemandType.RETAIL,
    channel: 'Retail',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 94000,
    createdAt: '2024-01-15T09:35:00Z',
    requestedDeliveryDate: '2024-01-20T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 7,
    productName: 'Cloud Runner 2',
    customer: 'On Paris Marais',
  },
  {
    orderId: 'ORD-2024-RET-006',
    demandType: DemandType.RETAIL,
    channel: 'Retail',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.GROUND,
    totalOrderValue: 88000,
    createdAt: '2024-01-20T15:05:00Z',
    requestedDeliveryDate: '2024-01-27T17:00:00Z',
    skuId: 'SKU-JACKET-002',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 8,
    productName: 'Performance Jacket',
    customer: 'On NYC SoHo',
  },
  {
    orderId: 'ORD-2024-RET-007',
    demandType: DemandType.RETAIL,
    channel: 'Retail',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 76500,
    createdAt: '2024-01-25T12:55:00Z',
    requestedDeliveryDate: '2024-01-31T17:00:00Z',
    skuId: 'SKU-JACKET-002',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 6,
    productName: 'Performance Jacket',
    customer: 'On Milan Centro',
  },
  {
    orderId: 'ORD-2024-RET-008',
    demandType: DemandType.RETAIL,
    channel: 'Retail',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.EXPRESS,
    totalOrderValue: 99000,
    createdAt: '2024-01-29T08:25:00Z',
    requestedDeliveryDate: '2024-02-01T17:00:00Z',
    skuId: 'SKU-JACKET-002',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 7,
    productName: 'Performance Jacket',
    customer: 'On Seoul Gangnam',
  },

  // Wholesale (7)
  {
    orderId: 'ORD-2024-WHO-001',
    demandType: DemandType.WHOLESALE,
    channel: 'Wholesale',
    customerTier: CustomerTier.VIP,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 460000,
    createdAt: '2024-01-05T13:10:00Z',
    requestedDeliveryDate: '2024-01-16T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 18,
    productName: 'Cloud Runner 2',
    customer: 'SportCo International',
  },
  {
    orderId: 'ORD-2024-WHO-002',
    demandType: DemandType.WHOLESALE,
    channel: 'Wholesale',
    customerTier: CustomerTier.VIP,
    shippingMethod: ShippingMethod.EXPRESS,
    totalOrderValue: 510000,
    createdAt: '2024-01-06T10:05:00Z',
    requestedDeliveryDate: '2024-01-15T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 15,
    productName: 'Cloud Runner 2',
    customer: 'FitZone Group',
  },
  {
    orderId: 'ORD-2024-WHO-003',
    demandType: DemandType.WHOLESALE,
    channel: 'Wholesale',
    customerTier: CustomerTier.VIP,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 405000,
    createdAt: '2024-01-12T09:45:00Z',
    requestedDeliveryDate: '2024-01-23T17:00:00Z',
    skuId: 'SKU-JACKET-002',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 14,
    productName: 'Performance Jacket',
    customer: 'Alpine Sports AG',
  },
  {
    orderId: 'ORD-2024-WHO-004',
    demandType: DemandType.WHOLESALE,
    channel: 'Wholesale',
    customerTier: CustomerTier.PREMIUM,
    shippingMethod: ShippingMethod.GROUND,
    totalOrderValue: 280000,
    createdAt: '2024-01-16T14:35:00Z',
    requestedDeliveryDate: '2024-01-30T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 13,
    productName: 'Cloud Runner 2',
    customer: 'RunWorld Ltd',
  },
  {
    orderId: 'ORD-2024-WHO-005',
    demandType: DemandType.WHOLESALE,
    channel: 'Wholesale',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 240000,
    createdAt: '2024-01-18T11:20:00Z',
    requestedDeliveryDate: '2024-01-29T17:00:00Z',
    skuId: 'SKU-JACKET-002',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 9,
    productName: 'Performance Jacket',
    customer: 'ActiveGear GmbH',
  },
  {
    orderId: 'ORD-2024-WHO-006',
    demandType: DemandType.WHOLESALE,
    channel: 'Wholesale',
    customerTier: CustomerTier.PREMIUM,
    shippingMethod: ShippingMethod.EXPRESS,
    totalOrderValue: 310000,
    createdAt: '2024-01-22T16:05:00Z',
    requestedDeliveryDate: '2024-02-02T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 10,
    productName: 'Cloud Runner 2',
    customer: 'Peak Athletics',
  },
  {
    orderId: 'ORD-2024-WHO-007',
    demandType: DemandType.WHOLESALE,
    channel: 'Wholesale',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.GROUND,
    totalOrderValue: 225000,
    createdAt: '2024-01-27T07:50:00Z',
    requestedDeliveryDate: '2024-02-06T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 9,
    productName: 'Cloud Runner 2',
    customer: 'Swift Retail',
  },

  // D2C (5)
  {
    orderId: 'ORD-2024-D2C-001',
    demandType: DemandType.D2C,
    channel: 'D2C',
    customerTier: CustomerTier.PREMIUM,
    shippingMethod: ShippingMethod.EXPRESS,
    totalOrderValue: 38000,
    createdAt: '2024-01-10T18:20:00Z',
    requestedDeliveryDate: '2024-01-13T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 5,
    productName: 'Cloud Runner 2',
    customer: 'Jane Smith',
  },
  {
    orderId: 'ORD-2024-D2C-002',
    demandType: DemandType.D2C,
    channel: 'D2C',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 26000,
    createdAt: '2024-01-19T09:40:00Z',
    requestedDeliveryDate: '2024-01-24T17:00:00Z',
    skuId: 'SKU-JACKET-002',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 6,
    productName: 'Performance Jacket',
    customer: 'Tom Mueller',
  },
  {
    orderId: 'ORD-2024-D2C-003',
    demandType: DemandType.D2C,
    channel: 'D2C',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.GROUND,
    totalOrderValue: 22000,
    createdAt: '2024-01-24T20:10:00Z',
    requestedDeliveryDate: '2024-02-01T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 4,
    productName: 'Cloud Runner 2',
    customer: 'Aiko Tanaka',
  },
  {
    orderId: 'ORD-2024-D2C-004',
    demandType: DemandType.D2C,
    channel: 'D2C',
    customerTier: CustomerTier.PREMIUM,
    shippingMethod: ShippingMethod.EXPRESS,
    totalOrderValue: 41000,
    createdAt: '2024-01-28T06:30:00Z',
    requestedDeliveryDate: '2024-01-31T17:00:00Z',
    skuId: 'SKU-JACKET-002',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 5,
    productName: 'Performance Jacket',
    customer: 'Priya Patel',
  },
  {
    orderId: 'ORD-2024-D2C-005',
    demandType: DemandType.D2C,
    channel: 'D2C',
    customerTier: CustomerTier.STANDARD,
    shippingMethod: ShippingMethod.STANDARD,
    totalOrderValue: 30000,
    createdAt: '2024-02-02T12:00:00Z',
    requestedDeliveryDate: '2024-02-07T17:00:00Z',
    skuId: 'SKU-RUNNER-001',
    warehouseId: DEMO_WAREHOUSE_ID,
    quantityRequested: 6,
    productName: 'Cloud Runner 2',
    customer: 'Lucas Silva',
  },
];
